# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: local
  hooks:
  - id: black
    name: black
    entry: black
    args: [--check]
    language: system
    types: [python]
  - id: isort
    name: isort
    entry: isort
    args: [--check-only]
    language: system
    types: [python]
