# Setup workflow to allow simpler CI config for our kindly-plugins monorepo
#
# References:
# - https://github.com/CircleCI-Public/api-preview-docs/blob/master/docs/setup-workflows.md
# - https://discuss.circleci.com/t/setup-workflows-open-preview/39516
version: 2.1

orbs:
  continuation: circleci/continuation@0.1.2

setup: true

jobs:
  setup:
    docker:
      - image: cimg/python:3.9.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pipenv install --deploy
      - run:
          name: Generate config
          command: |
            FORCE=$(if git log --pretty=format:"%s" HEAD^..HEAD | grep -q '\[force\]'; then echo "--force"; else echo ""; fi)
            pipenv run python -m build_versions.main --ci-config $FORCE
      - continuation/continue:
          configuration_path: .circleci/config_generated.yml

workflows:
  setup:
    jobs:
      - setup:
          filters:
            tags:
              only: /.*/
